; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Mar 07 2021 17:32:34 GMT-0500 (Eastern Standard Time)

